export const className = {
  container: {
    backgroundColor: '#f2f2f2',
    height: '100vh',
    backgroundImage: 'url("images/pattern.svg")',
  },
  loginBox: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    border: '1px solid #959595',
    borderRadius: '1rem',
    backgroundColor: 'white',
    boxShadow: "0px 30px 50px 0px rgba(0, 0, 0, 0.2)",
    padding: '1rem',
    alignSelf: 'center',
    maxWidth: '500px',
  },
  form: {
    width: '100%',
    marginTop: '2rem',
  },
  submit: {
    margin: '3rem 0 2rem',
    backgroundColor: 'rgb(32 33 30)',
    padding: '1rem 0',
    color: 'white',
    fontFamily: 'cursive',
    fontWeight: '700',
  },
  Font: {
    fontFamily: 'cursive',
  },
  circle: {
    backgroundColor: 'rgb(32 33 30)',
    transform: 'scale(5) translate(-43%, -15%)',
    borderRadius: '50%',
    padding: '8rem',
    alignSelf: 'start',
    boxShadow: 'rgba(0, 0, 0, 0.35) 0px 5px 15px',
    position: 'relative',
  },
  welcome: {
    position: 'absolute',
    textAlign: 'end',
    bottom: '30%',
    color: 'white',
    fontFamily: 'cursive',
    transition: 'right 0.5s ease-in-out',
  },
};
