export const classname = {
  BillingInfo: {
    margin: "2rem 0",
    display:'flex',
    flexDirection:'column',
    gap:'1rem',
  },
  title: {
    color: "var(--c-1-a, #151515)",
    fontFamily: "Open Sans",
    fontSize: "22px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "normal",
  },
  description: {
    color: "var(--c-1-c, #A9A9A9)",
    fontFamily: "Open Sans",
    fontSize: "12px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "normal",
    display: "flex",
    alignItems: "center",
    gap: "5px",
    justifyContent: "start",
    content: "unset",
  },
  formContainer:{
    display:'flex',
    justifyContent: "space-between",
    width: "100%",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    width: "100%",
  },
  label: {
    color: "var(--c-1-a, #151515)",
    lineHeight: "1",
    fontFamily: "Open Sans",
    fontSize: "1rem",
    fontWeight: 600,
  },
  field: {
    borderRadius: "12px",
    border: "1px solid var(--c-1-d, #D1D1D1)",
    background: "var(--c-1-h, #F9F9F9)",
    fontSize: "medium",
    padding: "0.8rem 0 0.8rem 1rem",
    textWrap: "nowrap",
    marginBottom: "1rem", 
  },
  differentAddresslabel: {
    color: "var(--c-1-a, #151515)",
    lineHeight: "1",
    fontFamily: "Open Sans",
    fontSize: "16px",
  },
  differentAddress: {
    borderRadius: "12px",
    border: "1px solid var(--c-1-d, #D1D1D1)",
    background: "var(--c-1-h, #F9F9F9)",
    width: "fit-content",
    padding: "0.2rem 1rem",
  },
  additionalInformationArea: {
    borderRadius: "12px",
    border: "1px solid var(--c-1-d, #D1D1D1)",
    background: "var(--c-1-h, #F9F9F9)",
    fontSize: "medium",
    padding: "1rem 10rem 5rem 1rem",
    textWrap: "nowrap",
    fontFamily: "Inter",
    marginBottom: "1rem",
  },
  submit: {
    borderRadius: "12px",
    border: "2px solid var(--c-2-b, #46760A)",
    background: "var(--c-2-a, #6A983C)",
    color: "var(--c-1-j, #FFF)",
    fontFamily: "Inter",
    fontSize: "1rem",
    fontWeight: 500,
    padding: "1rem 2rem",
    width: 'fit-content',
  },
  orderSummaryTitle: {
    padding: "1rem 1rem 2rem ",
    borderBottom: "1px solid #F9F9F9",
  },

  detail: {
    color: "var(--c-1-c, #A9A9A9)",
    fontFamily: "Open Sans",
    fontSize: "14px",
    fontStyle: "normal",
    fontWeight: 400,
    lineHeight: "normal",
  },
  detailDescription: {
    color: "black",
  },
  orderSummary: {
    display: "flex",
    alignItems: "start",
    marginBottom: "1rem",
    borderBottom: "1px solid #F9F9F9",
    padding: "1rem 0 0 1rem",
    width: "100%",
  },
  cardmedia: {
    display: "flex",
    flexDirection: "column",
  },
  descriptionContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    width: "100%",
  },
  icon: {
    color: "#E5704B",
    fontSize: "18px",
  },
  Removeicon: {
    color: "#151515",
    fontSize: "18px",
  },
  media: {
    width: "120px",
    height: "67px",
    objectFit: "contain",
  },
  price: {
    color: "var(--c-2-a, #6A983C)",
    fontFamily: "Open Sans",
    fontSize: "18px",
    fontWeight: 600,
  },
  quantity: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  subtotal: {
    margin: "1rem",
    display: "flex",
    flexDirection: "column",
    justifyContent: "start",
    width: "100%",
    gap: "1rem",
    marginBottom: "1rem",
    borderBottom: "1px solid #F9F9F9",
  },
  subtotalContent: {
    color: "var(--c-1-a, #151515)",
    fontFamily: "Open Sans",
    fontSize: "14px",
    fontWeight: 700,
    width: "90%",
    display: "flex",
    justifyContent: "space-between",
  },
  codeButton: {
    color: "black",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    width: "90%",
    borderRadius: "12px",
    border: `1px solid var(--c-1-d, #D1D1D1)`,
    background: "var(--c-1-h, #F9F9F9)",
  },
  orderSummaryContainer:{
    display:'flex',
    justifyContent: "center",
    height: 'fit-content',
  }
};
